### ISSUE TITLE
Pipeline not showing up

### ISSUE THREAD

**Issue by skarampatakis** [linkedpipes/uv2etl#2]
While I have managed to upload and executed the pipeline at Demo LP and, there is a problem with my local installation. The pipeline uploaded succesfully. But when open it, it's empty. However, when I download the pipeline everything seems to be OK. I can upload pipelines from Demo(e.g. ECB exchange rates) and see them. I can create new pipelines and see them. The problem is with the one created with uv2etl.

**Comment by skodapetr** [comment]
Could you please open the imported pipeline (uv2elt) and check that there are no errors in the developer console? 

If you import the uv2etl pipeline to demo, then export the pipeline and import to you local machine, does this work?

**Comment by skarampatakis** [comment]
```
templatesRepository.load
TypeError: Cannot read property '_ports' of undefined
    at createPorts (http://localhost:8080/app/components/pipelines/canvas/pipelineCanvasDirective.js:16:21)
    at createComponentCell (http://localhost:8080/app/components/pipelines/canvas/pipelineCanvasDirective.js:64:21)
    at Object.$scope.api.addComponent (http://localhost:8080/app/components/pipelines/canvas/pipelineCanvasDirective.js:643:36)
    at http://localhost:8080/app/components/pipelines/canvasView/pipelineEditCanvasCtrl.js:382:43
    at Array.forEach (native)
    at pipelineToCanvas (http://localhost:8080/app/components/pipelines/canvasView/pipelineEditCanvasCtrl.js:378:24)
    at $http.get.then.statusService.getFailed.title (http://localhost:8080/app/components/pipelines/canvasView/pipelineEditCanvasCtrl.js:474:17)
    at processQueue (http://localhost:8080/libraries/angularjs/1.4.1/angular.js:14551:28)
    at http://localhost:8080/libraries/angularjs/1.4.1/angular.js:14567:27
    at Scope.$eval (http://localhost:8080/libraries/angularjs/1.4.1/angular.js:15830:28)
```

I checked also to import the pipeline I have uploaded to Demo but the result is the same.

**Comment by skodapetr** [comment]
Are you using develop or master branch?

**Comment by skarampatakis** [comment]
Develop as suggested.

**Comment by skarampatakis** [comment]
Wait, maybe I have make a mistake while cloning. I will report back soon, building from scratch.

**Comment by skodapetr** [comment]
Could you share me the imported pipeline definition? 
You can see the definition on URL that is in the pipeline detail dialog.

**Comment by skarampatakis** [comment]
OK, it seems that building again solved the problem. The pipeline is finally showing up. The only problem I see for now is a duplicate GraphMerger instance, while it was not present at the original UV pipeline. 
![image](https://cloud.githubusercontent.com/assets/2419820/14949815/9dcc28c0-1055-11e6-84a0-0ceaa2bed81c.png)

That's not of much concern if the pipeline actually works, I just report it. Thank you again for the support.
